spring.application.name=PlayerStats(Final-Exam)
app.version = 1.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/footballdb
spring.datasource.username=${USERNAME_FOR_DB}
spring.datasource.password=${PASSWORD_FOR_DB}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect